version: '2.1'
services:
  pool:
    image: studybits/indy-pool:0.1.2
    ports:
    - "9701-9708:9701-9708"
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    # Host networking is used, because we need to know the pool IP at build time, which is kind-of tricky
    network_mode: "host"
  university-agent-rug:
    image: studybits/university-agent
    build:
      context: university-agent
    command: mvn package spring-boot:run
    network_mode: "host"
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    - NL_QUINTOR_STUDYBITS_UNIVERSITY_NAME=Rijksuniversiteit Groningen
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES:-mobile-test}
    depends_on:
      pool:
        condition: service_started
    healthcheck:
      test: curl -f http://localhost:8080/swagger-ui.html || exit 1
      interval: 5s
      timeout: 2s
      retries: 35
  university-agent-gent:
    build:
      context: university-agent
    command: mvn package spring-boot:run
    network_mode: "host"
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    - NL_QUINTOR_STUDYBITS_UNIVERSITY_NAME=Universiteit Gent
    - SERVER_PORT=8081
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES:-mobile-test}
    depends_on:
      pool:
        condition: service_started
    healthcheck:
      test: curl -f http://localhost:8081/swagger-ui.html || exit 1
      interval: 5s
      timeout: 2s
      retries: 35
  seeder:
    image: studybits/seeder
    build:
      context: seeder  
    network_mode: "host"
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    depends_on:
      pool:
        condition: service_started
      university-agent-rug:
        condition: service_healthy
      university-agent-gent:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /finished.txt ]"
      interval: 5s
      timeout: 2s
      retries: 35

  tests:
    build:
      context: university-agent
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    network_mode: "host"
    command: mvn verify
    depends_on:
      seeder:
        condition: service_healthy

